<a href="https://colab.research.google.com/github/annisaulia12/221230026-pengantar-ML/blob/main/week-02/latihan_praktikum_4_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
#Implementasi Operasi Dasar Neural Networks
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# SOLUSI 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    # Matrix multiplication: X (batch_size, n_features) @ W (n_features, 1)
    output = torch.matmul(X, W) + b
    return output

output = linear_layer(X, weights, bias)

# SOLUSI 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.maximum(tensor, torch.tensor(0.0))

activated = relu_activation(output)

# SOLUSI 3: Batch normalization sederhana
def simple_batch_norm(tensor, epsilon=1e-5):
    mean = torch.mean(tensor, dim=0, keepdim=True)  # Mean per feature
    std = torch.std(tensor, dim=0, keepdim=True)    # Std per feature
    normalized = (tensor - mean) / (std + epsilon)
    return normalized

normalized = simple_batch_norm(X)

# SOLUSI 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    batch_size = labels.shape[0]
    one_hot = torch.zeros(batch_size, num_classes)
    one_hot[torch.arange(batch_size), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

print("=== NEURAL NETWORK OPERATIONS ===")
print("Input shape:", X.shape)
print("Weights shape:", weights.shape)
print("Bias shape:", bias.shape)
print("Linear output shape:", output.shape)
print("ReLU output shape:", activated.shape)
print("Batch norm output shape:", normalized.shape)
print("Labels:", labels)
print("One-hot encoding shape:", one_hot.shape)
print("One-hot:\n", one_hot)

### BONUS: ADVANCED TENSOR OPERATIONS ###

'''SOLUSI: Matrix Multiplication dari Prinsip Dasar'''
def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    # Get dimensions
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Matrix dimensions don't match for multiplication")

    # Initialize result matrix
    result = torch.zeros(rows_A, cols_B)

    # Manual multiplication using loops
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]

    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("\n=== MATRIX MULTIPLICATION TEST ===")
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Manual result:\n", manual_result)
print("Torch matmul result:\n", torch_result)
print("Results are close:", torch.allclose(manual_result, torch_result))

# EXTRA: Tensor operations for image processing
print("\n=== IMAGE PROCESSING OPERATIONS ===")

# Simulate batch of images: (batch, channels, height, width)
batch_images = torch.randn(4, 3, 32, 32)  # 4 images, 3 channels, 32x32

# Resize operations
reshaped = batch_images.reshape(4, 3, 1024)  # Flatten spatial dimensions
permuted = batch_images.permute(0, 2, 3, 1)  # Change to (batch, height, width, channels)

print("Original images shape:", batch_images.shape)
print("Reshaped shape:", reshaped.shape)
print("Permuted shape:", permuted.shape)

# Convolution-like operation using unfold
def simple_conv2d(input_tensor, kernel_size=3):
    # Unfold to extract patches
    patches = input_tensor.unfold(2, kernel_size, 1).unfold(3, kernel_size, 1)
    print("Patches shape:", patches.shape)
    return patches

patches = simple_conv2d(batch_images)

# TEST ASSERTIONS
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"
assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"

print("\n✅ Semua assertions berhasil! Solusi benar.")

=== NEURAL NETWORK OPERATIONS ===
Input shape: torch.Size([32, 10])
Weights shape: torch.Size([10, 1])
Bias shape: torch.Size([1])
Linear output shape: torch.Size([32, 1])
ReLU output shape: torch.Size([32, 1])
Batch norm output shape: torch.Size([32, 10])
Labels: tensor([0, 2, 2, 1, 1, 1, 1, 2, 2, 2])
One-hot encoding shape: torch.Size([10, 3])
One-hot:
 tensor([[1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

=== MATRIX MULTIPLICATION TEST ===
Matrix A:
 tensor([[1., 2.],
        [3., 4.]])
Matrix B:
 tensor([[5., 6.],
        [7., 8.]])
Manual result:
 tensor([[19., 22.],
        [43., 50.]])
Torch matmul result:
 tensor([[19., 22.],
        [43., 50.]])
Results are close: True

=== IMAGE PROCESSING OPERATIONS ===
Original images shape: torch.Size([4, 3, 32, 32])
Reshaped shape: torch.Size([4, 3, 1024])
Permuted shape: t